---
ansible_connection: local
ansible_sudo: yes
temp_dir: /tmp
username: vagrant
home_dir: /home/vagrant
zsh_bin: /usr/bin/zsh
project_name: davedevenv

#ansible git settings
git_install_from_source: true
git_install_from_source_force_update: true
git_version: "2.24.1"

#docker settings
docker_edition: "ce"
# -- find on centos by "yum list docker-ce --showduplicates | sort -r"
docker_version: "18.06.1.ce-3.el7"
docker_package: "docker-{{ docker_edition }}-{{ docker_version }}"
docker_install_compose: true
docker_compose_version: "1.23.2"
# required for elasticsearch docker instance
vm_max_map_count: 262144
