---
ansible_connection: local
ansible_sudo: yes
temp_dir: /tmp
username: vagrant
home_dir: /home/vagrant
zsh_bin: /usr/bin/zsh
project_name: tms

# Postgresql related variables
postgresql_version: 9.5
postgresql_service_enabled: true

postgresql_databases:
  - name: "{{ username }}"
    owner: "{{ username }}"
  - name: "{{ project_name }}"
    owner: "{{ project_name }}" # optional; specify the owner of the database
    encoding: 'UTF-8'   # override global {{ postgresql_encoding }} variable per database

postgresql_users:
  - name: "{{ username }}"
    pass: "{{ username }}"
    encrypted: no
  - name: "{{ project_name }}"
    pass: "{{ project_name }}"
    encrypted: no       # denotes if the password is already encrypted.

postgresql_user_privileges:
  - name: "{{ username }}"
    db: "{{ username }}"
    priv: "ALL"
    role_attr_flags: "CREATEDB"
  - name: "{{ project_name }}"                   # user name
    db: "{{ project_name }}"                  # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags