---
ansible_connection: local
ansible_sudo: yes
temp_dir: /tmp
username: vagrant
home_dir: /home/vagrant
zsh_bin: /usr/bin/zsh
project_name: davedevenv

#ansible git settings
git_install_from_source: true
git_version: "2.18.0"
