---
- set_fact: dot_src_dir="/vagrant/dotfiles"
- set_fact: dot_dir="{{ home_dir }}/dotfiles"
- set_fact: auth_script="{{ home_dir }}/repos/auth/install.sh"
- name: install symlinks
  package: name=symlinks state=present
- name: link dotfiles to home directory
  file:
    src: "{{ dot_src_dir }}"
    dest: "{{ dot_dir }}"
    state: link
- name: run configuration setup script
  become_user: "{{ username }}"
  shell: "sh setup.sh chdir={{ dot_dir }}"
- name: set sysctl to support elasticsearch dockers
  sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    sysctl_set: yes
- name: check if certificates available
  become_user: "{{ username }}"
  stat:
    path: "{{ auth_script }}"
  register: auth_script_file
- name: install and configure certificates
  become_user: "{{ username }}"
  shell: "{{ auth_script }}"
  when: auth_script_file.stat.exists == True
