---
- name: update all installed packages
  package: name=* update_cache=yes state=present
- name: install common required packages
  apt: "name={{ item }} state=present"
  with_items:
    - software-properties-common
    - build-essential
    - unzip
    - libcurl4-gnutls-dev
    - libxml2
    - libxml2-dev
    - openssl
    - tmux
    - bzip2
    - sqlite3
    - tree
    - xclip
    - jq
    - cairo-devel
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install development packages required by common RedHat / Centos packages
  yum: "name={{ item }} state=present"
  with_items:
    - '@Development Tools'
    - epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: install common required packages
  yum: "name={{ item }} state=present"
  with_items:
    - tree
    - jq
    - xclip
    - unzip
    - yum-utils
    - zlib
    - zlib-devel
    - bzip2-devel
    - readline-devel
    - readline
    - openssl-devel
    - openssl
    - sqlite-devel
    - epel-release
    - ack
    - tmux
    - lsb-core-noarch
    - libXScrnSaver
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
