---
- name: update all installed packages
  yum: name=* update_cache=yes state=present
- name: install common required packages
  yum: "name={{ item }} state=present"
  with_items:
    - git
    - unzip
    - yum-utils
    - zlib
    - zlib-devel
    - bzip2-devel
    - readline-devel
    - readline
    - openssl-devel
    - openssl
    - gitflow
    - qt5-qtbase
    - sqlite-devel
- name: install development tools
  yum: "name={{ item }} state=present"
  with_items:
    - '@Development Tools'
