---
- name: update all installed packages
  apt: name=* update_cache=yes state=present
- name: install common required packages
  apt: "name={{ item }} state=present"
  with_items:
    - software-properties-common
    - build-essential
    - unzip
    - libcurl4-gnutls-dev
    - libxml2
    - libxml2-dev
    - openssl
