---
- name: installation facts
  set_fact:
    pyenv_root: "{{ home_dir }}/.pyenv"
    nvm_root: "{{ home_dir }}/.nvm"
    nvm_version: 0.33.11
- name: install ruby and javascript
  apt: "name={{ item }} update_cache=yes state=present"
  with_items:
    - ruby-full
    - nodejs
    - npm
- name: check if pyenv installed
  command: command -v pyenv
  register: pyenv_check
  ignore_errors: True
  become_user: "{{ username }}"
- name: install pyenv
  become_user: "{{ username }}"
  when: pyenv_check is failed
  block:
  - name: get pyenv automatic installer script
    get_url:
      url: https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
      dest: /tmp/install_pyenv.sh
  - name: install pyenv using the automatic installer
    shell: "sh install_pyenv.sh chdir=/tmp"
    args:
      creates: "{{ pyenv_root }}"
  - name: configure zsh for pyenv
    blockinfile:
      backup: true
      dest: "{{ home_dir }}/.zshrc"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
      insertafter: "# BEGIN ANSIBLE MANAGED BLOCK - pyenv"
      content: |
          export PATH="{{ home_dir }}/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
- name: check if nvm installed
  command: command -v nvm
  register: nvm_check
  ignore_errors: True
  become_user: "{{ username }}"
- name: install nvm
  become_user: "{{ username }}"
  when: nvm_check is failed
  block:
  - name: get pyenv automatic installer script
    get_url:
      url: "https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh"
      dest: /tmp/install_nvm.sh
  - name: install nvm using the automatic installer
    shell: "{{ zsh_bin }} install_nvm.sh chdir=/tmp"
    args:
      creates: "{{ nvm_root }}"
  - name: configure zsh for nvm
    blockinfile:
      backup: true
      dest: "{{ home_dir }}/.zshrc"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - nvm"
      insertafter: "# BEGIN ANSIBLE MANAGED BLOCK - nvm"
      content: |
          export NVM_DIR="{{ nvm_root }}"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
