---
- name: install LaTex files (for building PDFs)
  yum: "name={{ item }} state=present"
  with_items:
    - texlive
    - texlive-latex
    - texlive-xetex
    - texlive-collection-latex
    - texlive-collection-latexrecommended
    - texlive-xetex-def
    - texlive-collection-xetex
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

