---
- name: install LaTex files (for building PDFs)
  yum:
    name:
      - pandoc
      - texlive
      - texlive-latex
      - texlive-xetex
      - texlive-collection-latex
      - texlive-collection-latexrecommended
      - texlive-xetex-def
      - texlive-collection-xetex
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

