---
- include: devtools.yml
- include: vim.yml
- include: tmux.yml
- include: oh_my_zsh.yml
- include: custom_config.yml
# - name: make zsh the current shell
  # shell: "{{ zsh_bin }}"
# - include: languages.yml
# - include: browsers.yml
# - include: desktop.yml
# - include: guestadditions.yml
# - include: powerline.yml
