---
- include: devtools.yml
- include: custom_config.yml
- include: vim.yml
- include: oh_my_zsh.yml
- include: languages.yml
- include: tmux.yml
- include: powerline.yml
- include: desktop.yml
- include: browsers.yml
- include: guestadditions.yml
# - include: latex.yml

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker

- name: Update all packages (Ubuntu)
  apt:
    upgrade: dist
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update kernel packages (CentOS)
  yum:
    name: 'kernel*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
