---
- include: devtools.yml
- name: check for nvim installation
  command: which nvim
  become_user: vagrant
  register: nvim_check
  ignore_errors: True
- name: check for tmux installation
  command: which tmux
  become_user: vagrant
  register: tmux_check
  ignore_errors: True
- include: nvim.yml
  when: nvim_check is failed
- include: tmux.yml
  when: tmux_check is failed
# - include: oh_my_zsh.yml
# - include: custom_config.yml
# - name: make zsh the current shell
  # shell: "{{ zsh_bin }}"
# - include: languages.yml
# - include: browsers.yml
# - include: desktop.yml
# - include: guestadditions.yml
# - include: powerline.yml
