---
- set_fact: powerline_fonts_dir="{{ temp_dir }}/powerline-fonts"
- name: check for powerline fonts
  register: powerline_fonts
  command: "find {{ powerline_fonts_dir }} -type d"
  ignore_errors: True
  become: true
  become_user: "{{ username }}"
- name: install minimum necessary tools (centos)
  yum:
    name:
      - python36
      - python36-pip
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: install powerline for vim and tmux
  shell: pip3 install powerline-status
- name: install powerline fonts
  when: powerline_fonts is failed
  block:
    - name: clone and/or update powerline fonts
      git: "repo=https://github.com/powerline/fonts.git dest={{ powerline_fonts_dir }} clone=yes update=yes force=yes"
    - name: install powerline fonts
      shell: "zsh install.sh chdir={{ powerline_fonts_dir }}"
