---
- set_fact: powerline_fonts_dir="{{ temp_dir }}/powerline-fonts"
- name: install powerline for vim and tmux
  shell: pip install powerline-status
- name: clone and/or update powerline fonts
  git: "repo=https://github.com/powerline/fonts.git dest={{ powerline_fonts_dir }} clone=yes update=yes force=yes"
- name: install powerline fonts
  shell: "zsh install.sh chdir={{ powerline_fonts_dir }}"
