---
- name: install vim dependencies
  yum: "name={{ item }} state=present"
  with_items:
    - ncurses-devel
- name: download vim source code
  get_url: "url=https://github.com/vim/vim/archive/master.zip dest={{ temp_dir }}/master.zip"
- name: Unpackage vim source code
  unarchive: "src={{ temp_dir }}/master.zip dest={{temp_dir}}"
- name: configure vim for installation
  command: '"{{ item }}" chdir={{temp_dir}}/vim-master'
  with_items:
    - ./configure
- name: Make and make install the vim target
  make: "chdir={{ temp_dir }}/vim-master target=install"