---
- set_fact: vim_dir="{{ temp_dir }}/vim-master"
- name: check for vim installation
  shell: "vim --version | head -1 | cut -d ' ' -f 5 | cut -d '.' -f 1"
  become: true
  become_user: "{{ username }}"
  register: vim_version
  ignore_errors: True
- name: install vim
  when: vim_version is failed or vim_version.stdout|int < 8
  block:
  - name: uninstall existing vim
    package:
      name:
        - vim
        - vim-tiny
      state: absent
  - name: install vim dependencies (Ubuntu / Debian)
    apt:
      name:
        - libncurses5-dev
        - libgnome2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - libatk1.0-dev
        - libbonoboui2-dev
        - libcairo2-dev
        - libx11-dev
        - libxpm-dev
        - libxt-dev
        - python-dev
        - python3-dev
        - ruby-dev
        - lua5.1
        - libperl-dev
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: install vim dependencies (CentOS / RHEL)
    yum:
      name:
        - ncurses-devel
        - python36
        - python36-devel
        - libX11-devel
      state: present
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Unpackage vim source code
    unarchive:
      src: "https://github.com/vim/vim/archive/master.zip"
      dest: "{{ temp_dir }}"
      remote_src: true
      creates: "{{ vim_dir }}"
  - name: configure vim for installation
    shell: >
      ./configure
      --enable-multibyte
      --enable-python3interp=dynamic
      --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu/
      --with-features=huge
      --enable-fontset
      --enable-largefile
      --with-compiledby="vagrant"
      --enable-fail-if-missing
    args:
      chdir: "{{ vim_dir }}"
  - name: Make and make install the vim target
    make: "chdir={{ vim_dir }} target=install"
