---
- hosts: controller
  become: true
  become_method: sudo
  remote_user: root

  pre_tasks:
    - name: remove git (debian)
      apt: "name=git state=absent"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: remove git (centos)
      yum: "name=git state=absent"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  roles:
    - geerlingguy.git
    - geerlingguy.docker
    - common
