---
- hosts: controller
  become: true
  become_method: sudo
  remote_user: root

  pre_tasks:
    - name: remove git (debian)
      package: "name=git state=absent"

  roles:
    - geerlingguy.git
    - geerlingguy.docker
    - common
